BINDIR = /usr/local/bin
SHAREDIR = /usr/local/share/third

install:
	@echo "Installing third ..."
	mkdir -vp $(BINDIR)
	install -v third.py $(BINDIR)/
	@echo
	@echo "Installing shared files ..."
	mkdir -vp $(SHAREDIR)
	install -v share/* $(SHAREDIR)/
	@echo
	@echo "Installation complete."
	@echo
	@echo "Run third by executing $(BINDIR)/third.py."
